# **Tensor Operations**

**Tensors**: Tensor, in relation to machine learning, is a generalization of scalars, vectors, and matrices as seen in the table below.

![img](https://cdn.iisc.talentsprint.com/CDS/Images/tensors.JPG)

* From the above explanation, you might have understood that Tensor operations are nothing but matrix operations.

**Tensorflow**:
We are introducing Tensorflow here, a widely used library for Machine Learning, specifically deep learning. Tensorflow's name is directly derived from its core framework: Tensor and all the computations carried out involve Tensor and its operations.TensorFlow was developed by the Google Brain team and first released under the Apache License 2.0 in 2015.
* In the following sections, we will see few commonly used operations of Tensor using both NumPy and TensorFlow Library.

In [4]:
# Importing required packages

import numpy as np
import tensorflow as tf

## Defining and slicing a 2D/1D-Tensor

### NumPy

In [6]:
a=np.array([[1,2],[2,3],[6,7]])             # Defining a 2D array in Numpy
print(a)                                    # printing the array
print('shape = ',a.shape)                   # '.shape' method gives the number of rows and columns in the form of a tuple
print('dimension = ',a.ndim)                # It gives dimension of the array
print('size =',np.size(a))                  # size always gives total number of elements in any array
print('lengths = ',len(a))                  # In 2D it gives the number of rows in an array
print('data structure type : ',type(a))     # It gives the type of data structure
a.dtype                                     # it gives type of data stored in array

[[1 2]
 [2 3]
 [6 7]]
shape =  (3, 2)
dimension =  2
size = 6
lengths =  3
data structure type :  <class 'numpy.ndarray'>


dtype('int64')

#### Slicing: We are going to define a 2D Matrix as given in the image below and apply the slicing operations.

![2Dimg](https://cdn.iisc.talentsprint.com/CDS/Images/2D_array_slicing.JPG)

In [7]:
## Creating a 2D array
a2d = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
a2d

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [8]:
# slicing the 2nd index row
a2d[2]

array([ 7,  8,  9, 10])

In [9]:
# zeroth row
a2d[0]

array([1, 2, 3, 4])

In [10]:
# The first value before coma is for row index and the second value after coma is for column index.
a2d[1,3]

np.int64(7)

In [11]:
# This can also used.
a2d[1][3]

np.int64(7)

In [12]:
# Using negative index
a2d[-2,-3]

np.int64(5)

In [13]:
# from the very beginning to -2 indexed row (i.e -3 and -2 indexed row) and -3,-4 indexed columns are sliced
a2d[:-1,:-2]

array([[1, 2],
       [4, 5]])

In [14]:
# from the very beginning to 1 indexed row, i.e 0 and 1 index row sliced. 2 is not included.
a2d[:2]

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [15]:
# ( 0 ,1 ) indexed rows and 2 to last indexed columns are sliced.
a2d[:2, 2:]

array([[3, 4],
       [6, 7]])

In [16]:
# 1 indexed row and (0,1) indexed columns are sliced .
a2d[1, :2]

array([4, 5])

In [17]:
# Explain yourself?
a2d[:2, 2]

array([3, 6])

In [18]:
# All rows and 0 column ( from the very beginning, but 1 not included i.e. zeroth column ) sliced.
a2d[:, :1]

array([[1],
       [4],
       [7]])

In [19]:
print('Initial Matrix = ',a2d)
# This is an assignment operation, a2d  itself gets changed.
a2d[:2, 1:] = 0
print('Matrix after above assigned operations = ',a2d)

Initial Matrix =  [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
Matrix after above assigned operations =  [[ 1  0  0  0]
 [ 4  0  0  0]
 [ 7  8  9 10]]


### TensorFlow
**tf.Variable**: There are multiple ways of defining/forming a Tensor in Tensorflow, tf.Variable is one of those. A tf.Variable represents a tensor whose value can be changed by running operations on it. Specific operations allow you to read and modify the values of this tensor. Higher-level libraries like tf.keras use tf.Variable to store model parameters that keep changing/updating with subsequent learning steps.

**tf.Constant**: This is another way of creating a Tensor but the tensor made through this cannot be updated but can be called multiple times with only 1 copy in the memory.

In [ ]:
a_tf = tf.Variable([[1,2],[2,3],[6,7]])
print(a_tf)
print("Shape of the input tensor is", tf.shape(a_tf)) # Returns a tensor containing the shape of the input tensor
print("Rank of the input tensor is", tf.rank(a_tf)) # Returns the rank of a tensor
# print(a_tf.ndim) -->  This operation is not valid for tf.variable object.
print("Size of the input tensor is", tf.size(a_tf)) # Returns the size of a tensor

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [6, 7]], dtype=int32)>
Shape of the input tensor is tf.Tensor([3 2], shape=(2,), dtype=int32)
Rank of the input tensor is tf.Tensor(2, shape=(), dtype=int32)
Size of the input tensor is tf.Tensor(6, shape=(), dtype=int32)
